id = "menhir"
name = "Menhir"
version = "0.0.1"
schema_version = 1
authors = ["Matthew Else <matthewelse1997@gmail.com>"]
description = "Menhir language support for Zed"
repository = "https://github.com/matthewelse/zed-menhir"

[grammars.menhir]
repository = "https://github.com/Kerl13/tree-sitter-menhir"
commit = "be8866a6bcc2b563ab0de895af69daeffa88fe70"
